// <auto-generated />
using System;
using ESII.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESII.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319180025_CorrigirTabelas")]
    partial class CorrigirTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESII.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("convite", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("projeto", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecoHora")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalHoras")
                        .HasColumnType("numeric");

                    b.Property<int?>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("relatorio", (string)null);
                });

            modelBuilder.Entity("ESII.Models.RelatorioProj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecoTarefas")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("relatorioproj", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatorioProjId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("RelatorioProjId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("HorasDia")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("utilizador", (string)null);
                });

            modelBuilder.Entity("ESII.Models.UtilizadorProjeto", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("integer");

                    b.HasKey("UtilizadorId", "ProjetoId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("utilizadorprojeto", (string)null);
                });

            modelBuilder.Entity("ESII.Models.Convite", b =>
                {
                    b.HasOne("ESII.Models.Projeto", "Projeto")
                        .WithMany("Convites")
                        .HasForeignKey("ProjetoId");

                    b.HasOne("ESII.Models.Utilizador", "Utilizador")
                        .WithMany("Convites")
                        .HasForeignKey("UtilizadorId");

                    b.Navigation("Projeto");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ESII.Models.Projeto", b =>
                {
                    b.HasOne("ESII.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("ESII.Models.Utilizador", "Utilizador")
                        .WithMany("Projetos")
                        .HasForeignKey("UtilizadorId");

                    b.Navigation("Cliente");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ESII.Models.Relatorio", b =>
                {
                    b.HasOne("ESII.Models.Utilizador", "Utilizador")
                        .WithMany("Relatorios")
                        .HasForeignKey("UtilizadorId");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ESII.Models.RelatorioProj", b =>
                {
                    b.HasOne("ESII.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("ESII.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");

                    b.Navigation("Cliente");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ESII.Models.Tarefa", b =>
                {
                    b.HasOne("ESII.Models.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoId");

                    b.HasOne("ESII.Models.RelatorioProj", "RelatorioProj")
                        .WithMany()
                        .HasForeignKey("RelatorioProjId");

                    b.HasOne("ESII.Models.Utilizador", "Utilizador")
                        .WithMany("Tarefas")
                        .HasForeignKey("UtilizadorId");

                    b.Navigation("Projeto");

                    b.Navigation("RelatorioProj");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ESII.Models.UtilizadorProjeto", b =>
                {
                    b.HasOne("ESII.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESII.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("ESII.Models.Projeto", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("ESII.Models.Utilizador", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("Projetos");

                    b.Navigation("Relatorios");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
